# используем язык java. Travis CI поддерживает разные языки.
language: java

# указываем текущую версию jdk: например openjdk8 или oraclejdk14
jdk: oraclejdk14

# используем режим обычного пользователя для сборки проекта.
# sudo: false

# подключаем postgresql
services:
  - postgresql

before_install:
  - psql -c 'create database grabber;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo

# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      -yarmail@yandex.ru
    on_success: never # default: change
    on_failure: never # default: always

# Вставляем ключ, полученный с codecov.io
env:
  global:
    - CODECOV_TOKEN="071066cb-3f60-474f-abed-55ae57065753"